config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'finance/index'
  get 'finance/show'
  get 'summary/index'
  get 'report/index'
  get 'sales_report/index'
  resources :employees
  # devise_for :accounts, controllers: {
  #   sessions: 'accounts/sessions'
  # }

  #setting the vehicles index page as the home page
  root 'vehicles#index', as: 'vehicles_index'

  resources :quotes do
    member do
      get 'calculations'
      end
    end
  resources :vehicles do
    member do
      get 'price'
    end
  end
  resources :customers

  get 'summary', to: 'summary#index'
  get 'reports', to: 'report#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :vehicle
  belongs_to :customer
  belongs_to :employee


  scope :is_sold, -> {where(sold: true)}
  scope :not_sold, -> {where(sold: false)}
  #setting quote compund period to a class variable
  @@compound = 4
  @@interest_rate = 0.08
  @start_balance
  @end_balance
  @principal
  @am_int 


  def self.compound
    @@compound
  end

  def self.interest_rate
    @@interest_rate
  end


  def wholesale
    self.wholesale_price = self.vehicle.price
  end
  #method to round to 5 significant digits
  def rounder5(to_round)
    to_round.round(5)
  end

  #methods for quote calculations
  def mark_up_amt
    rounder5(self.vehicle.price * 0.082)
  end

  def tax_amt
    rounder5((self.vehicle.price + mark_up_amt) * 0.043)
  end

  def total_amt
    rounder5(self.vehicle.price + mark_up_amt + tax_amt)
  end

  def finance_amt
    rounder5(total_amt - self.down_payment)
  end

  def i_rate
    rounder5(Quote.interest_rate / Quote.compound)
  end

  def number_payments
    (self.term * Quote.compound).to_i
  end

  def ammoritization_numerator
    rounder5(total_amt * (i_rate * ((1 + i_rate) ** number_payments)))
  end

  def ammoritization_denominator
    rounder5(((1 + i_rate) ** number_payments) -1)
  end

  def ammortization_payments
    rounder5(ammoritization_numerator/ ammoritization_denominator)
  end

  def a_interest(amt)
    amt * i_rate
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  load_and_authorize_resource
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.not_sold.paginate(:page => params[:page], per_page: 50)

    if params[:search]
      @search_term = params[:search]
      @quotes = @quotes.search_by(@search_term).paginate(:page => params[:page], per_page: 50)
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = QuotePdf.new(@quote, view_context)

        send_data pdf.render,
          filename: "quote_#{@quote.id}-#{@quote.customer.full_name}#{@quote.vehicle.vehicle_details}",
          type: 'application/pdf'
      end
    end
  end

  def calculations
    quote = Quote.find(params[:id])
    render json: QuotePresenter.new(quote)
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:vehicle_id, :customer_id, :employee_id, :wholesale_price, :term, :markup_price, :tax, :total_price, :sold)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.collection_select :vehicle_id, Vehicle.available, :id, :vehicle_details %>
    <p>Base Price <span id="price"></span></p>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.collection_select :customer_id, Customer.all, :id, :full_name %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.collection_select :employee_id, Employee.is_sales_person, :id, :full_name %>
  </div>

  <div class="field">
    <%= form.label :term %>
    <%= form.select :term, [['3 years', 3], ['4 years', 4], ['5 years', 5]] %>
  </div>

  <div class="field">
    <%= form.label :sold %>
    <%= form.check_box :sold %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<table class="report">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Vehicle</th>
      <th>Base Price</th>
      <th>Fees</th>
      <th>Tax</th>
      <th>Total Price</th>
      <th>Term</th>
      <th># of payments</th>
      <th>Quarterly Payments</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= quote.customer.full_name%></td>
    <td><%= quote.vehicle.vehicle_details%></td>
    <td><%= number_to_currency(quote.wholesale)%></td>
    <td><%= number_to_currency(quote.mark_up_amt)%></td>
    <td><%= number_to_currency(quote.tax_amt)%></td>
    <td><%= number_to_currency(quote.total_amt)%></td>
    <td><%= quote.term%></td>
    <td><%= quote.number_payments%></td>
    <td><%= number_to_currency(quote.ammortization_payments)%></td>
  </tr>
</tbody>
</table>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Vehicle</th>
      <th>Customer</th>
      <th>Sales person</th>
      <th>Wholesale price</th>
      <th>Markup price</th>
      <th>Tax</th>
      <th>Total price</th>
      <th>Term</th>
      <th>Quartely Payment</th>
      <th>Number of Payments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= quote.vehicle.vehicle_details %></td>
        <td><%= quote.customer.full_name %></td>
        <td><%= quote.employee.full_name %></td>
        <td><%= number_to_currency(quote.wholesale) %></td>
        <td><%= number_to_currency(quote.mark_up_amt) %></td>
        <td><%= number_to_currency(quote.tax_amt) %></td>
        <td><%= number_to_currency(quote.total_amt) %></td>
        <td><%= quote.term %></td>
        <td><%= number_to_currency(quote.ammortization_payments) %></td>
        <td><%= quote.number_payments.to_i %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

<br>

<%= will_paginate @quotes %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle:</strong>
  <%= @quote.vehicle.vehicle_details %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.full_name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @quote.employee.full_name %>
</p>

<p>
  <strong>Wholesale price:</strong>
  <%= number_to_currency(@quote.vehicle.price) %>
</p>

<p>
  <strong>Fees:</strong>
  <%= number_to_currency(@quote.mark_up_amt) %>
</p>

<p>
  <strong>Sales Tax:</strong>
  <%= number_to_currency(@quote.tax_amt) %>
</p>

<p>
  <strong>Interest Rate %:</strong>
  <%= 100 * (Quote.interest_rate) %>
</p>

<p>
  <strong>Total Amount</strong>
  <%= number_to_currency(@quote.total_amt) %>
</p>

<p>
  <strong>Term:</strong>
  <%= @quote.term.to_i %>
</p>

<p>
  <strong># of Payments:</strong>
  <%= @quote.number_payments %>
</p>

<p>
  <strong>Quartely Payment:</strong>
  <%= number_to_currency(@quote.ammortization_payments) %>
</p>
<% if current_user.role == 'finance' || current_user.role == 'admin' %>
<p>Ammoritization Schedule for <%=@quote.vehicle.vehicle_details%></p>
<table>
  <thead>
    <tr>
      <th>Payment</th>
      <th>Starting Balance</th>
      <th>Interest</th>
      <th>Principal</th>
      <th>Remaining Balance</th>
    </tr>
  </thead>
  <tbody>
    <% i = 1 %>
    <% balance = @quote.total_amt%>
    <% interest = @quote.a_interest(balance)%>
    <% prin = @quote.ammortization_payments - interest %>
    <% @quote.number_payments.times do %>
    <tr class="<%= cycle('odd', 'even')%>">
      <td><%= i %></td>
      <td><%= number_to_currency(balance) %></td>
      <td><%= number_to_currency(interest)%></td>
      <td><%= number_to_currency(prin) %></td>
      <td><%= number_to_currency(balance - prin) %></td>
    </tr>
    <% balance = (balance - prin) %>
    <% interest = @quote.a_interest(balance)%>
    <% prin = @quote.ammortization_payments - interest%>
    <% i += 1 %>
    <% end %>
  </tbody>
</table>
<% end %>


<%= link_to 'PDF', quote_path(@quote, format: 'pdf') %> |
<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>