config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'finance/index'
  get 'finance/show'
  get 'summary/index'
  get 'report/index'
  get 'sales_report/index'
  resources :employees
  # devise_for :accounts, controllers: {
  #   sessions: 'accounts/sessions'
  # }

  #setting the vehicles index page as the home page
  root 'vehicles#index', as: 'vehicles_index'

  resources :quotes do
    member do
      get 'calculations'
      end
    end
  resources :vehicles do
    member do
      get 'price'
    end
  end
  resources :customers

  get 'summary', to: 'summary#index'
  get 'reports', to: 'report#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :quotes
  has_one_attached :vehicle_image

  scope :no_quote, -> {includes(:quotes).where(quotes: {id: nil})}
  scope :quote_not_sold, -> {includes(:quotes).where(quotes: {sold: false})}
  scope :available, -> {quote_not_sold.or(Vehicle.no_quote)}


  #validations
  validates :vin, presence: true, uniqueness: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :year, numericality: { greater_than_or_equal_to: 1}
  validates :model, presence: true
  validates :color, presence: true
  validates :make, presence: true


  #method to return vehicle details in collection select
  def vehicle_details
    "#{year} #{make} #{model}"
  end

  private
  #method to ensure vehicles with quotes cannot be deleted
  def ensure_not_referenced_by_quotes
    unless quotes.empty?
      errors.add(:base, 'Quotes for this vehicle')
      throw :abort
    end
  end

  def self.search_by(search_term)
    where("LOWER(vin) LIKE :search_term OR LOWER(make) LIKE :search_term
    OR LOWER(model) LIKE :search_term OR LOWER(color) LIKE :search_term OR
    LOWER(car_type) LIKE :search_term ", search_term: "%#{search_term.downcase}%")
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  load_and_authorize_resource :notice => "Improper credentials"
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.available.paginate(:page => params[:page], per_page: 50)
    if params[:search]
      @search_term = params[:search]
      @vehicles = Vehicle.search_by(@search_term).paginate(:page =>  params[:page], per_page: 50)
    end

  end

  def price
    vehicle = Vehicle.find(params[:id])
    render json: vehicle
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:vin, :color, :car_type, :model, :make, :year, :price, :vehicle_image, :name )
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vin %>
    <%= form.text_field :vin %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.select :color, [['Black'], ['Blue'], ['Red'], ['Gray'], ['Yellow'], ['Green'], ['Orange'], ['White'],
                             ['Silver'], ['Navy Blue'], ['Gold'], ['Brown'], ['Beige'], ['Light Brown'],
                             ['Dark Red'], ['Burgundy'], ['Bright Red'], ['Maroon'], ['Purple'], ['Pink'],
                             ['Metallic White'], ['Metallic Green'], ['Metallic Red'], ['Metallic Blue'],
                             ['Metallic Black'], ['Metallic Orange'], ['Metallic Grey'], ['Metallic Yellow'],
                             ['Metallic Gold'], ['Metallic Purple'], ['Gunmetal Grey'], ['Aqua Blue']]  %>
  </div>

  <div class="field">
    <%= form.label :make %>
    <%= form.select :make, [['Acura'], ['Alfa Romeo'], ['Aston Martin'], ['Audi'], ['Bentley'], ['BMW'], ['Bugatti'],
                            ['Buick'], ['Cadillac'], ['Chevrolet'], ['Chrysler'], ['Citroen'], ['Dodge'], ['Ferrari'],
                            ['Fiat'], ['Ford'], ['Geely'], ['General Motors'], ['GMC'], ['Honda'], ['Hyundai'],
                            ['Infiniti'], ['Jaguar'], ['Jeep'], ['Kia'], ['Koenigsegg'], ['Lamborghini'], ['Land Rover'],
                            ['Lexus'], ['Maserati'], ['Mazda'], ['McLaren'], ['Mercedes-Benz'], ['Mini'], ['Mitsubishi'],
                            ['Nissan'], ['Pagani'], ['Peugeot'], ['Porsche'], ['Ram'], ['Renault'], ['Rolls Royce'],
                            ['Saab'], ['Subaru'], ['Suzuki'], ['Tata Motors'], ['Tesla'], ['Toyota'], ['Volkswagen'],
                            ['Volvo']] %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :vehicle_image %>
    <%= form.file_field :vehicle_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<%= form_for "", url: vehicles_path, role: "search", method: :get do %>
  <%= text_field_tag :search, @search_term, placeholder: "Search..." %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Vin</th>
      <th>Color</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% cache @vehicles do %>
      <% @vehicles.each do |vehicle| %>
        <% cache vehicle do %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td><%= vehicle.vin %></td>
          <td><%= vehicle.color %></td>
          <td><%= vehicle.make %></td>
          <td><%= vehicle.model %></td>
          <td><%= vehicle.year %></td>
          <td><%= number_to_currency(vehicle.price) %></td>
          <td><%= link_to 'Show', vehicle %></td>
          <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
          <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

<br>

<%= will_paginate @vehicles %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vin:</strong>
  <%= @vehicle.vin %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicle.color %>
</p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@vehicle.price) %>
</p>
<%if @vehicle.vehicle_image.attached? %>
<p>
  <strong>Vehicle Image:</strong>
  <%= image_tag @vehicle.vehicle_image %>
</p>
<%end %>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>